[package]
name = "chirpstack-udp-bridge"
repository="https://github.com/brocaar/chirpstack-udp-bridge/"
license="MIT"
version = "3.0.0-test.1"
authors = ["Orne Brocaar <info@brocaar.com>"]
edition = "2018"
publish = false

[dependencies]
chirpstack_api = { version = "3.9.1", default-features = false }
serde_json = "1.0.60"
zmq = "0.9.2"
clap = "2.33.3"
hex = "0.4.2"
toml = "0.5.8"
serde = { version = "1.0.118", features = ["derive"] }
log = "0.4.11"
simple_logger = "1.11.0"
uuid = { version = "0.8.1", features = ["v4"] }
syslog = "5.0.0"
rand = "0.8.0"
chrono = "0.4.19"
base64 = "0.13.0"
prost = "0.6.1"
prost-types = "0.6.1"
prometheus = "0.11.0"
lazy_static = "1.4.0"

[features]
default = ['zmq/vendored']
