version: "2"
services:
  chirpstack-udp-forwarder:
    build:
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - ./:/chirpstack-udp-forwarder
      - ./.rust/target:/chirpstack-udp-forwarder/target
      - ./.rust/.cargo/registry/index:/usr/local/cargo/registry/index
      - ./.rust/.cargo/registry/cache:/usr/local/cargo/registry/cache
      - ./.rust/.cargo/git/db:/usr/local/cargo/git/db
